import {
  AlertCircle,
  ArrowRight,
  Bell,
  Book,
  BookOpen,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  ChartBar,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  CircleCheck,
  CirclePlus,
  Clipboard,
  Clock,
  Database,
  Download,
  Eye,
  FileText,
  Folder,
  Globe,
  Home,
  Image as LucideImage,
  Inbox,
  Info,
  Layers,
  ListFilter,
  Loader,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Navigation,
  Pen,
  Pencil,
  Phone,
  PhoneCall,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Tag,
  Trash2,
  TriangleAlert,
  User,
  UserPlus,
  Users,
  X,
} from 'lucide-react-native';
import React from 'react';
import { StyleProp, ViewStyle } from 'react-native';

const ICON_MAP: Record<string, React.ComponentType<{ size?: number; color?: string; style?: StyleProp<ViewStyle> }>> = {
  'alert-circle': AlertCircle,
  'alert-triangle': TriangleAlert,
  'arrow-right': ArrowRight,
  'bar-chart-2': ChartBar,
  'bell': Bell,
  'book': Book,
  'book-open': BookOpen,
  'briefcase': Briefcase,
  'building-2': Building2,
  'calendar': Calendar,
  'camera': Camera,
  'check': Check,
  'check-circle': CircleCheck,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'city': Building2,
  'clipboard': Clipboard,
  'clock': Clock,
  'database': Database,
  'download': Download,
  'earth': Globe,
  'edit-2': Pencil,
  'edit-3': Pen,
  'eye': Eye,
  'file-document-outline': FileText,
  'file-text': FileText,
  'filter': ListFilter,
  'folder': Folder,
  'globe': Globe,
  'home': Home,
  'image': LucideImage,
  'inbox': Inbox,
  'info': Info,
  'layers': Layers,
  'loader': Loader,
  'lock': Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  'mail': Mail,
  'map-pin': MapPin,
  'navigation': Navigation,
  'pen': Pen,
  'pencil': Pencil,
  'phone': Phone,
  'phone-call': PhoneCall,
  'plus': Plus,
  'plus-circle': CirclePlus,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'save': Save,
  'search': Search,
  'settings': Settings,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'tag': Tag,
  'trash-2': Trash2,
  'user': User,
  'user-plus': UserPlus,
  'users': Users,
  'x': X,
};

interface IconProps {
  name: string;
  size?: number;
  color?: string;
  style?: StyleProp<ViewStyle>;
}

export default function Icon({ name, size = 24, color = '#000000', style }: IconProps) {
  const LucideIcon = ICON_MAP[name];
  if (!LucideIcon) return null;
  return <LucideIcon size={size} color={color} style={style} />;
}
